USE [master]
GO
/****** Object:  Database [OnboardAPI]    Script Date: 3/28/2022 3:07:36 PM ******/
CREATE DATABASE [OnboardAPI]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'OnboardAPI', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.FINTRAKSQL\MSSQL\DATA\OnboardAPI.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'OnboardAPI_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.FINTRAKSQL\MSSQL\DATA\OnboardAPI_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [OnboardAPI] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [OnboardAPI].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [OnboardAPI] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [OnboardAPI] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [OnboardAPI] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [OnboardAPI] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [OnboardAPI] SET ARITHABORT OFF 
GO
ALTER DATABASE [OnboardAPI] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [OnboardAPI] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [OnboardAPI] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [OnboardAPI] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [OnboardAPI] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [OnboardAPI] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [OnboardAPI] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [OnboardAPI] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [OnboardAPI] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [OnboardAPI] SET  DISABLE_BROKER 
GO
ALTER DATABASE [OnboardAPI] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [OnboardAPI] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [OnboardAPI] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [OnboardAPI] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [OnboardAPI] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [OnboardAPI] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [OnboardAPI] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [OnboardAPI] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [OnboardAPI] SET  MULTI_USER 
GO
ALTER DATABASE [OnboardAPI] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [OnboardAPI] SET DB_CHAINING OFF 
GO
ALTER DATABASE [OnboardAPI] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [OnboardAPI] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [OnboardAPI] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [OnboardAPI] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [OnboardAPI] SET QUERY_STORE = OFF
GO
USE [OnboardAPI]
GO
/****** Object:  Table [dbo].[TBL_STATEANDLGA]    Script Date: 3/28/2022 3:07:36 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TBL_STATEANDLGA](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[STATE] [varchar](100) NOT NULL,
	[LGA] [varchar](100) NOT NULL,
	[STATEID] [int] NULL,
 CONSTRAINT [PK_StateLGA] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TblCustomer]    Script Date: 3/28/2022 3:07:36 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TblCustomer](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[AccountNumber] [varchar](50) NULL,
	[Firstname] [varchar](100) NULL,
	[Othernames] [varchar](100) NULL,
	[Surname] [varchar](100) NULL,
	[Email] [varchar](200) NULL,
	[Phone] [varchar](100) NULL,
	[Addressid] [int] NULL,
 CONSTRAINT [PK_TblCustomer] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TblCustomeraddress]    Script Date: 3/28/2022 3:07:36 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TblCustomeraddress](
	[ID] [int] NULL,
	[CUSTOMERID] [int] NULL,
	[STATEID] [int] NULL,
	[ADDRESS] [varchar](500) NULL,
	[HOMETOWN] [varchar](500) NULL,
	[POBOX] [varchar](500) NULL,
	[COUNTRY] [varchar](100) NULL
) ON [PRIMARY]
GO
SET IDENTITY_INSERT [dbo].[TBL_STATEANDLGA] ON 
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (1, N'Abuja', N'Gwagwalada', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (2, N'Abuja', N'Kuje', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (3, N'Abuja', N'Abaji', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (4, N'Abuja', N'Abuja Municipal', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (5, N'Abuja', N'Bwari', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (6, N'Abuja', N'Kwali', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (7, N'Abia', N'Aba North', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (8, N'Abia', N'Aba South', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (9, N'Abia', N'Arochukwu', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (10, N'Abia', N'Bende', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (11, N'Abia', N'Ikwuano', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (12, N'Abia', N'Isiala-Ngwa North', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (13, N'Abia', N'Isiala-Ngwa South', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (14, N'Abia', N'Isuikwato', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (15, N'Abia', N'Obi Nwa', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (16, N'Abia', N'Ohafia', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (17, N'Abia', N'Osisioma', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (18, N'Abia', N'Ngwa', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (19, N'Abia', N'Ugwunagbo', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (20, N'Abia', N'Ukwa East', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (21, N'Abia', N'Ukwa West', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (22, N'Abia', N'Umuahia North', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (23, N'Abia', N'Umuahia South', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (24, N'Abia', N'Umu-Neochi', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (25, N'Adamawa', N'Demsa', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (26, N'Adamawa', N'Fufore', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (27, N'Adamawa', N'Ganaye', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (28, N'Adamawa', N'Gireri', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (29, N'Adamawa', N'Gombi', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (30, N'Adamawa', N'Guyuk', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (31, N'Adamawa', N'Hong', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (32, N'Adamawa', N'Jada', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (33, N'Adamawa', N'Lamurde', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (34, N'Adamawa', N'Madagali', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (35, N'Adamawa', N'Maiha ', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (36, N'Adamawa', N'Mayo-Belwa', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (37, N'Adamawa', N'Michika', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (38, N'Adamawa', N'Mubi North', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (39, N'Adamawa', N'Mubi South', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (40, N'Adamawa', N'Numan', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (41, N'Adamawa', N'Shelleng', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (42, N'Adamawa', N'Song', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (43, N'Adamawa', N'Toungo', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (44, N'Adamawa', N'Yola North', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (45, N'Adamawa', N'Yola South', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (46, N'Akwa Ibom', N'Abak', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (47, N'Akwa Ibom', N'Eastern Obolo', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (48, N'Akwa Ibom', N'Eket', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (49, N'Akwa Ibom', N'Esit Eket', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (50, N'Akwa Ibom', N'Essien Udim', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (51, N'Akwa Ibom', N'Etim Ekpo', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (52, N'Akwa Ibom', N'Etinan', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (53, N'Akwa Ibom', N'Ibeno', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (54, N'Akwa Ibom', N'Ibesikpo Asutan', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (55, N'Akwa Ibom', N'Ibiono Ibom', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (56, N'Akwa Ibom', N'Ika', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (57, N'Akwa Ibom', N'Ikono', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (58, N'Akwa Ibom', N'Ikot Abasi', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (59, N'Akwa Ibom', N'Ikot Ekpene', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (60, N'Akwa Ibom', N'Ini', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (61, N'Akwa Ibom', N'Itu', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (62, N'Akwa Ibom', N'Mbo', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (63, N'Akwa Ibom', N'Mkpat Enin', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (64, N'Akwa Ibom', N'Nsit Atai', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (65, N'Akwa Ibom', N'Nsit Ibom', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (66, N'Akwa Ibom', N'Nsit Ubium', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (67, N'Akwa Ibom', N'Obot Akara', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (68, N'Akwa Ibom', N'Okobo', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (69, N'Akwa Ibom', N'Onna', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (70, N'Akwa Ibom', N'Oron ', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (71, N'Akwa Ibom', N'Oruk Anam', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (72, N'Akwa Ibom', N'Udung Uko', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (73, N'Akwa Ibom', N'Ukanafun', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (74, N'Akwa Ibom', N'Uruan', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (75, N'Akwa Ibom', N'Urue-Offong/Oruko', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (76, N'Akwa Ibom', N'Uyo', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (77, N'Anambra', N'Aguata', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (78, N'Anambra', N'Anambra East', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (79, N'Anambra', N'Anambra West', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (80, N'Anambra', N'Anaocha', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (81, N'Anambra', N'Awka North', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (82, N'Anambra', N'Awka South', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (83, N'Anambra', N'Ayamelum', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (84, N'Anambra', N'Dunukofia', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (85, N'Anambra', N'Ekwusigo', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (86, N'Anambra', N'Idemili North', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (87, N'Anambra', N'Idemili south', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (88, N'Anambra', N'Ihiala', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (89, N'Anambra', N'Njikoka', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (90, N'Anambra', N'Nnewi North', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (91, N'Anambra', N'Nnewi South', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (92, N'Anambra', N'Ogbaru', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (93, N'Anambra', N'Onitsha North', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (94, N'Anambra', N'Onitsha South', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (95, N'Anambra', N'Orumba North', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (96, N'Anambra', N'Orumba South', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (97, N'Anambra', N'Oyi ', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (98, N'Bauchi', N'Alkaleri', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (99, N'Bauchi', N'Bauchi', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (100, N'Bauchi', N'Bogoro', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (101, N'Bauchi', N'Dambam', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (102, N'Bauchi', N'Darazo', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (103, N'Bauchi', N'Dass', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (104, N'Bauchi', N'Ganjuwa', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (105, N'Bauchi', N'Giade', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (106, N'Bauchi', N'Itas/Gadau', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (107, N'Bauchi', N'Jama''are', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (108, N'Bauchi', N'Katagum', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (109, N'Bauchi', N'Kirfi', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (110, N'Bauchi', N'Misau', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (111, N'Bauchi', N'Ningi', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (112, N'Bauchi', N'Shira', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (113, N'Bauchi', N'Tafawa-Balewa', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (114, N'Bauchi', N'Toro', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (115, N'Bauchi', N'Warji', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (116, N'Bauchi', N'Zaki ', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (117, N'Bayelsa', N'Brass', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (118, N'Bayelsa', N'Ekeremor', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (119, N'Bayelsa', N'Kolokuma/Opokuma', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (120, N'Bayelsa', N'Nembe', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (121, N'Bayelsa', N'Ogbia', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (122, N'Bayelsa', N'Sagbama', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (123, N'Bayelsa', N'Southern Jaw', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (124, N'Bayelsa', N'Yenegoa ', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (125, N'Benue', N'Ado', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (126, N'Benue', N'Agatu', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (127, N'Benue', N'Apa', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (128, N'Benue', N'Buruku', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (129, N'Benue', N'Gboko', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (130, N'Benue', N'Guma', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (131, N'Benue', N'Gwer East', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (132, N'Benue', N'Gwer West', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (133, N'Benue', N'Katsina-Ala', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (134, N'Benue', N'Konshisha', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (135, N'Benue', N'Kwande', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (136, N'Benue', N'Logo', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (137, N'Benue', N'Makurdi', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (138, N'Benue', N'Obi', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (139, N'Benue', N'Ogbadibo', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (140, N'Benue', N'Oju', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (141, N'Benue', N'Okpokwu', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (142, N'Benue', N'Ohimini', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (143, N'Benue', N'Oturkpo', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (144, N'Benue', N'Tarka', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (145, N'Benue', N'Ukum', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (146, N'Benue', N'Ushongo', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (147, N'Benue', N'Vandeikya', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (148, N'Borno', N' Abadam', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (149, N'Borno', N'Askira/Uba', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (150, N'Borno', N'Bama', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (151, N'Borno', N'Bayo', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (152, N'Borno', N'Biu', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (153, N'Borno', N'Chibok', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (154, N'Borno', N'Damboa', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (155, N'Borno', N'Dikwa', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (156, N'Borno', N'Gubio', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (157, N'Borno', N'Guzamala', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (158, N'Borno', N'Gwoza', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (159, N'Borno', N'Hawul', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (160, N'Borno', N'Jere', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (161, N'Borno', N'Kaga', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (162, N'Borno', N'Kala/Balge', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (163, N'Borno', N'Konduga', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (164, N'Borno', N'Kukawa', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (165, N'Borno', N'Kwaya Kusar', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (166, N'Borno', N'Mafa', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (167, N'Borno', N'Magumeri', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (168, N'Borno', N'Maiduguri', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (169, N'Borno', N'Marte', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (170, N'Borno', N'Mobbar', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (171, N'Borno', N'Monguno', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (172, N'Borno', N'Ngala', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (173, N'Borno', N'Nganzai', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (174, N'Borno', N'Shani ', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (175, N'Cross River', N'Akpabuyo', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (176, N'Cross River', N'Odukpani', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (177, N'Cross River', N'Akamkpa', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (178, N'Cross River', N'Biase', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (179, N'Cross River', N'Abi', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (180, N'Cross River', N'Ikom', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (181, N'Cross River', N'Yarkur', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (182, N'Cross River', N'Odubra', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (183, N'Cross River', N'Boki', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (184, N'Cross River', N'Ogoja', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (185, N'Cross River', N'Yala', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (186, N'Cross River', N'Obanliku', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (187, N'Cross River', N'Obudu', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (188, N'Cross River', N'Calabar South', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (189, N'Cross River', N'Etung', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (190, N'Cross River', N'Bekwara', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (191, N'Cross River', N'Bakassi', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (192, N'Cross River', N'Calabar Municipality', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (193, N'Delta', N'Oshimili', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (194, N'Delta', N'Aniocha', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (195, N'Delta', N'Aniocha South', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (196, N'Delta', N'Ika South', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (197, N'Delta', N'Ika North-East', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (198, N'Delta', N'Ndokwa West', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (199, N'Delta', N'Ndokwa East', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (200, N'Delta', N'Isoko south', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (201, N'Delta', N'Isoko North', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (202, N'Delta', N'Bomadi', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (203, N'Delta', N'Burutu', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (204, N'Delta', N'Ughelli South', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (205, N'Delta', N'Ughelli North', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (206, N'Delta', N'Ethiope West', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (207, N'Delta', N'Ethiope East', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (208, N'Delta', N'Sapele', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (209, N'Delta', N'Okpe', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (210, N'Delta', N'Warri North', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (211, N'Delta', N'Warri South', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (212, N'Delta', N'Uvwie', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (213, N'Delta', N'Udu', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (214, N'Delta', N'Warri Central', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (215, N'Delta', N'Ukwani', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (216, N'Delta', N'Oshimili North', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (217, N'Delta', N'Patani', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (218, N'Ebonyi ', N'Afikpo South', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (219, N'Ebonyi ', N'Afikpo North', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (220, N'Ebonyi ', N'Onicha', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (221, N'Ebonyi ', N'Ohaozara', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (222, N'Ebonyi ', N'Abakaliki', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (223, N'Ebonyi ', N'Ishielu', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (224, N'Ebonyi ', N'lkwo', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (225, N'Ebonyi ', N'Ezza', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (226, N'Ebonyi ', N'Ezza South', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (227, N'Ebonyi ', N'Ohaukwu', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (228, N'Ebonyi ', N'Ebonyi', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (229, N'Ebonyi ', N'Ivo ', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (230, N'Edo', N'Esan North-East', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (231, N'Edo', N'Esan Central', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (232, N'Edo', N'Esan West', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (233, N'Edo', N'Egor', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (234, N'Edo', N'Ukpoba', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (235, N'Edo', N'Central', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (236, N'Edo', N'Etsako Central', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (237, N'Edo', N'Igueben', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (238, N'Edo', N'Oredo', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (239, N'Edo', N'Ovia SouthWest', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (240, N'Edo', N'Ovia South-East', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (241, N'Edo', N'Orhionwon', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (242, N'Edo', N'Uhunmwonde', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (243, N'Edo', N'Etsako East ', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (244, N'Edo', N'Esan South-East ', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (245, N'Ekiti', N'Ado', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (246, N'Ekiti', N'Ekiti-East', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (247, N'Ekiti', N'Ekiti-West ', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (248, N'Ekiti', N'Emure/Ise/Orun', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (249, N'Ekiti', N'Ekiti South-West', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (250, N'Ekiti', N'Ikare', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (251, N'Ekiti', N'Irepodun', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (252, N'Ekiti', N'Ijero, ', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (253, N'Ekiti', N'Ido/Osi', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (254, N'Ekiti', N'Oye', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (255, N'Ekiti', N'Ikole', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (256, N'Ekiti', N'Moba', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (257, N'Ekiti', N'Gbonyin', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (258, N'Ekiti', N'Efon', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (259, N'Ekiti', N'Ise/Orun ', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (260, N'Ekiti', N'Ilejemeje.', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (261, N'Enugu', N'Enugu South, ', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (262, N'Enugu', N'Igbo-Eze South', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (263, N'Enugu', N'Enugu North', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (264, N'Enugu', N'Nkanu', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (265, N'Enugu', N'Udi Agwu', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (266, N'Enugu', N'Oji-River', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (267, N'Enugu', N'Ezeagu', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (268, N'Enugu', N'IgboEze North', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (269, N'Enugu', N'Isi-Uzo', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (270, N'Enugu', N'Nsukka', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (271, N'Enugu', N'Igbo-Ekiti', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (272, N'Enugu', N'Uzo-Uwani', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (273, N'Enugu', N'Enugu East', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (274, N'Enugu', N'Aninri', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (275, N'Enugu', N'Nkanu East', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (276, N'Enugu', N'Udenu', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (277, N'Gombe', N'Akko', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (278, N'Gombe', N'Balanga', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (279, N'Gombe', N'Billiri', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (280, N'Gombe', N'Dukku', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (281, N'Gombe', N'Kaltungo', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (282, N'Gombe', N'Kwami', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (283, N'Gombe', N'Shomgom', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (284, N'Gombe', N'Funakaye', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (285, N'Gombe', N'Gombe', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (286, N'Gombe', N'Nafada/Bajoga ', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (287, N'Gombe', N'Yamaltu/Delta', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (288, N'Imo', N'Aboh-Mbaise', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (289, N'Imo', N'Ahiazu-Mbaise', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (290, N'Imo', N'Ehime-Mbano', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (291, N'Imo', N'Ezinihitte', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (292, N'Imo', N'Ideato North', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (293, N'Imo', N'Ideato South', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (294, N'Imo', N'Ihitte/Uboma', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (295, N'Imo', N'Ikeduru', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (296, N'Imo', N'Isiala Mbano', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (297, N'Imo', N'Isu', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (298, N'Imo', N'Mbaitoli', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (299, N'Imo', N'Mbaitoli', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (300, N'Imo', N'Ngor-Okpala', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (301, N'Imo', N'Njaba', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (302, N'Imo', N'Nwangele', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (303, N'Imo', N'Nkwerre', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (304, N'Imo', N'Obowo', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (305, N'Imo', N'Oguta', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (306, N'Imo', N'Ohaji/Egbema', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (307, N'Imo', N'Okigwe', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (308, N'Imo', N'Orlu', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (309, N'Imo', N'Orsu', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (310, N'Imo', N'Oru East', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (311, N'Imo', N'Oru West', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (312, N'Imo', N'Owerri-Municipal', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (313, N'Imo', N'Owerri North', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (314, N'Imo', N'Owerri West ', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (315, N'Jigawa', N'Auyo', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (316, N'Jigawa', N'Babura', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (317, N'Jigawa', N'Birni Kudu', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (318, N'Jigawa', N'Biriniwa', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (319, N'Jigawa', N'Buji', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (320, N'Jigawa', N'Dutse', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (321, N'Jigawa', N'Gagarawa', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (322, N'Jigawa', N'Garki', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (323, N'Jigawa', N'Gumel', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (324, N'Jigawa', N'Guri', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (325, N'Jigawa', N'Gwaram', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (326, N'Jigawa', N'Gwiwa', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (327, N'Jigawa', N'Hadejia', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (328, N'Jigawa', N'Jahun', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (329, N'Jigawa', N'Kafin Hausa', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (330, N'Jigawa', N'Kaugama Kazaure', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (331, N'Jigawa', N'Kiri Kasamma', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (332, N'Jigawa', N'Kiyawa', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (333, N'Jigawa', N'Maigatari', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (334, N'Jigawa', N'Malam Madori', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (335, N'Jigawa', N'Miga', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (336, N'Jigawa', N'Ringim', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (337, N'Jigawa', N'Roni', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (338, N'Jigawa', N'Sule-Tankarkar', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (339, N'Jigawa', N'Taura ', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (340, N'Jigawa', N'Yankwashi ', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (341, N'Kaduna', N'Birni-Gwari', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (342, N'Kaduna', N'Chikun', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (343, N'Kaduna', N'Giwa', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (344, N'Kaduna', N'Igabi', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (345, N'Kaduna', N'Ikara', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (346, N'Kaduna', N'jaba', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (347, N'Kaduna', N'Jema''a', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (348, N'Kaduna', N'Kachia', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (349, N'Kaduna', N'Kaduna North', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (350, N'Kaduna', N'Kaduna South', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (351, N'Kaduna', N'Kagarko', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (352, N'Kaduna', N'Kajuru', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (353, N'Kaduna', N'Kaura', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (354, N'Kaduna', N'Kauru', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (355, N'Kaduna', N'Kubau', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (356, N'Kaduna', N'Kudan', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (357, N'Kaduna', N'Lere', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (358, N'Kaduna', N'Makarfi', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (359, N'Kaduna', N'Sabon-Gari', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (360, N'Kaduna', N'Sanga', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (361, N'Kaduna', N'Soba', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (362, N'Kaduna', N'Zango-Kataf', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (363, N'Kaduna', N'Zaria ', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (364, N'Kano', N'Ajingi', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (365, N'Kano', N'Albasu', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (366, N'Kano', N'Bagwai', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (367, N'Kano', N'Bebeji', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (368, N'Kano', N'Bichi', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (369, N'Kano', N'Bunkure', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (370, N'Kano', N'Dala', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (371, N'Kano', N'Dambatta', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (372, N'Kano', N'Dawakin Kudu', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (373, N'Kano', N'Dawakin Tofa', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (374, N'Kano', N'Doguwa', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (375, N'Kano', N'Fagge', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (376, N'Kano', N'Gabasawa', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (377, N'Kano', N'Garko', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (378, N'Kano', N'Garum', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (379, N'Kano', N'Mallam', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (380, N'Kano', N'Gaya', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (381, N'Kano', N'Gezawa', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (382, N'Kano', N'Gwale', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (383, N'Kano', N'Gwarzo', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (384, N'Kano', N'Kabo', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (385, N'Kano', N'Kano Municipal', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (386, N'Kano', N'Karaye', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (387, N'Kano', N'Kibiya', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (388, N'Kano', N'Kiru', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (389, N'Kano', N'kumbotso', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (390, N'Kano', N'Kunchi', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (391, N'Kano', N'Kura', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (392, N'Kano', N'Madobi', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (393, N'Kano', N'Makoda', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (394, N'Kano', N'Minjibir', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (395, N'Kano', N'Nasarawa', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (396, N'Kano', N'Rano', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (397, N'Kano', N'Rimin Gado', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (398, N'Kano', N'Rogo', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (399, N'Kano', N'Shanono', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (400, N'Kano', N'Sumaila', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (401, N'Kano', N'Takali', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (402, N'Kano', N'Tarauni', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (403, N'Kano', N'Tofa', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (404, N'Kano', N'Tsanyawa', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (405, N'Kano', N'Tudun Wada', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (406, N'Kano', N'Ungogo', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (407, N'Kano', N'Warawa', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (408, N'Kano', N'Wudil', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (409, N'Katsina', N'Bakori', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (410, N'Katsina', N'Batagarawa', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (411, N'Katsina', N'Batsari', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (412, N'Katsina', N'Baure', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (413, N'Katsina', N'Bindawa', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (414, N'Katsina', N'Charanchi', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (415, N'Katsina', N'Dandume', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (416, N'Katsina', N'Danja', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (417, N'Katsina', N'Dan Musa', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (418, N'Katsina', N'Daura', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (419, N'Katsina', N'Dutsi', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (420, N'Katsina', N'Dutsin-Ma', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (421, N'Katsina', N'Faskari', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (422, N'Katsina', N'Funtua', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (423, N'Katsina', N'Ingawa', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (424, N'Katsina', N'Jibia', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (425, N'Katsina', N'Kafur', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (426, N'Katsina', N'Kaita', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (427, N'Katsina', N'Kankara', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (428, N'Katsina', N'Kankia', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (429, N'Katsina', N'Katsina', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (430, N'Katsina', N'Kurfi', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (431, N'Katsina', N'Kusada', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (432, N'Katsina', N'Mai''Adua', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (433, N'Katsina', N'Malumfashi', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (434, N'Katsina', N'Mani', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (435, N'Katsina', N'Mashi', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (436, N'Katsina', N'Matazuu', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (437, N'Katsina', N'Musawa', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (438, N'Katsina', N'Rimi', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (439, N'Katsina', N'Sabuwa', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (440, N'Katsina', N'Safana', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (441, N'Katsina', N'Sandamu', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (442, N'Katsina', N'Zango ', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (443, N'Kebbi', N'Aleiro', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (444, N'Kebbi', N'Arewa-Dandi', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (445, N'Kebbi', N'Argungu', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (446, N'Kebbi', N'Augie', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (447, N'Kebbi', N'Bagudo', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (448, N'Kebbi', N'Birnin Kebbi', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (449, N'Kebbi', N'Bunza', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (450, N'Kebbi', N'Dandi ', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (451, N'Kebbi', N'Fakai', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (452, N'Kebbi', N'Gwandu', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (453, N'Kebbi', N'Jega', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (454, N'Kebbi', N'Kalgo ', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (455, N'Kebbi', N'Koko/Besse', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (456, N'Kebbi', N'Maiyama', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (457, N'Kebbi', N'Ngaski', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (458, N'Kebbi', N'Sakaba', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (459, N'Kebbi', N'Shanga', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (460, N'Kebbi', N'Suru', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (461, N'Kebbi', N'Wasagu/Danko', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (462, N'Kebbi', N'Yauri', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (463, N'Kebbi', N'Zuru ', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (464, N'Kogi', N'Adavi', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (465, N'Kogi', N'Ajaokuta', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (466, N'Kogi', N'Ankpa', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (467, N'Kogi', N'Bassa', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (468, N'Kogi', N'Dekina', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (469, N'Kogi', N'Ibaji', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (470, N'Kogi', N'Idah', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (471, N'Kogi', N'Igalamela-Odolu', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (472, N'Kogi', N'Ijumu', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (473, N'Kogi', N'Kabba/Bunu', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (474, N'Kogi', N'Kogi', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (475, N'Kogi', N'Lokoja', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (476, N'Kogi', N'Mopa-Muro', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (477, N'Kogi', N'Ofu', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (478, N'Kogi', N'Ogori/Mangongo', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (479, N'Kogi', N'Okehi', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (480, N'Kogi', N'Okene', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (481, N'Kogi', N'Olamabolo', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (482, N'Kogi', N'Omala', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (483, N'Kogi', N'Yagba East ', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (484, N'Kogi', N'Yagba West', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (485, N'Kwara', N'Asa', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (486, N'Kwara', N'Baruten', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (487, N'Kwara', N'Edu', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (488, N'Kwara', N'Ekiti', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (489, N'Kwara', N'Ifelodun', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (490, N'Kwara', N'Ilorin East', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (491, N'Kwara', N'Ilorin West', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (492, N'Kwara', N'Irepodun', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (493, N'Kwara', N'Isin', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (494, N'Kwara', N'Kaiama', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (495, N'Kwara', N'Moro', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (496, N'Kwara', N'Offa', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (497, N'Kwara', N'Oke-Ero', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (498, N'Kwara', N'Oyun', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (499, N'Kwara', N'Pategi ', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (500, N'Lagos', N'Agege', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (501, N'Lagos', N'Ajeromi-Ifelodun', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (502, N'Lagos', N'Alimosho', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (503, N'Lagos', N'Amuwo-Odofin', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (504, N'Lagos', N'Apapa', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (505, N'Lagos', N'Badagry', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (506, N'Lagos', N'Epe', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (507, N'Lagos', N'Eti-Osa', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (508, N'Lagos', N'Ibeju/Lekki', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (509, N'Lagos', N'Ifako-Ijaye ', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (510, N'Lagos', N'Ikeja', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (511, N'Lagos', N'Ikorodu', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (512, N'Lagos', N'Kosofe', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (513, N'Lagos', N'Lagos Island', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (514, N'Lagos', N'Lagos Mainland', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (515, N'Lagos', N'Mushin', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (516, N'Lagos', N'Ojo', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (517, N'Lagos', N'Oshodi-Isolo', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (518, N'Lagos', N'Shomolu', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (519, N'Lagos', N'Surulere', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (520, N'Nasarawa', N'Akwanga', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (521, N'Nasarawa', N'Awe', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (522, N'Nasarawa', N'Doma', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (523, N'Nasarawa', N'Karu', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (524, N'Nasarawa', N'Keana', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (525, N'Nasarawa', N'Keffi', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (526, N'Nasarawa', N'Kokona', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (527, N'Nasarawa', N'Lafia', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (528, N'Nasarawa', N'Nasarawa', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (529, N'Nasarawa', N'Nasarawa-Eggon', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (530, N'Nasarawa', N'Obi', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (531, N'Nasarawa', N'Toto', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (532, N'Nasarawa', N'Wamba ', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (533, N'Niger', N'Agaie', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (534, N'Niger', N'Agwara', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (535, N'Niger', N'Bida', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (536, N'Niger', N'Borgu', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (537, N'Niger', N'Bosso', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (538, N'Niger', N'Chanchaga', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (539, N'Niger', N'Edati', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (540, N'Niger', N'Gbako', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (541, N'Niger', N'Gurara', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (542, N'Niger', N'Katcha', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (543, N'Niger', N'Kontagora ', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (544, N'Niger', N'Lapai', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (545, N'Niger', N'Lavun', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (546, N'Niger', N'Magama', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (547, N'Niger', N'Mariga', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (548, N'Niger', N'Mashegu', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (549, N'Niger', N'Mokwa', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (550, N'Niger', N'Muya', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (551, N'Niger', N'Pailoro', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (552, N'Niger', N'Rafi', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (553, N'Niger', N'Rijau', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (554, N'Niger', N'Shiroro', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (555, N'Niger', N'Suleja', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (556, N'Niger', N'Tafa', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (557, N'Niger', N'Wushishi', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (558, N'Ogun', N'Abeokuta North', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (559, N'Ogun', N'Abeokuta South', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (560, N'Ogun', N'Ado-Odo/Ota', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (561, N'Ogun', N'Egbado North', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (562, N'Ogun', N'Egbado South', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (563, N'Ogun', N'Ewekoro', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (564, N'Ogun', N'Ifo', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (565, N'Ogun', N'Ijebu East', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (566, N'Ogun', N'Ijebu North', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (567, N'Ogun', N'Ijebu North East', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (568, N'Ogun', N'Ijebu Ode', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (569, N'Ogun', N'Ikenne', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (570, N'Ogun', N'Imeko-Afon', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (571, N'Ogun', N'Ipokia', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (572, N'Ogun', N'Obafemi-Owode', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (573, N'Ogun', N'Ogun Waterside', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (574, N'Ogun', N'Odeda', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (575, N'Ogun', N'Odogbolu', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (576, N'Ogun', N'Remo North', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (577, N'Ogun', N'Shagamu', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (578, N'Ondo', N'Akoko North East', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (579, N'Ondo', N'Akoko North West', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (580, N'Ondo', N'Akoko South Akure East', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (581, N'Ondo', N'Akoko South West', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (582, N'Ondo', N'Akure North', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (583, N'Ondo', N'Akure South', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (584, N'Ondo', N'Ese-Odo', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (585, N'Ondo', N'Idanre', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (586, N'Ondo', N'Ifedore', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (587, N'Ondo', N'Ilaje', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (588, N'Ondo', N'Ile-Oluji', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (589, N'Ondo', N'Okeigbo', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (590, N'Ondo', N'Irele', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (591, N'Ondo', N'Odigbo', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (592, N'Ondo', N'Okitipupa', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (593, N'Ondo', N'Ondo East', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (594, N'Ondo', N'Ondo West', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (595, N'Ondo', N'Ose', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (596, N'Ondo', N'Owo ', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (597, N'Osun', N'Aiyedade', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (598, N'Osun', N'Aiyedire', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (599, N'Osun', N'Atakumosa East', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (600, N'Osun', N'Atakumosa West', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (601, N'Osun', N'Boluwaduro', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (602, N'Osun', N'Boripe', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (603, N'Osun', N'Ede North', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (604, N'Osun', N'Ede South', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (605, N'Osun', N'Egbedore', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (606, N'Osun', N'Ejigbo', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (607, N'Osun', N'Ife Central', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (608, N'Osun', N'Ife East', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (609, N'Osun', N'Ife North', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (610, N'Osun', N'Ife South', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (611, N'Osun', N'Ifedayo', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (612, N'Osun', N'Ifelodun', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (613, N'Osun', N'Ila', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (614, N'Osun', N'Ilesha East', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (615, N'Osun', N'Ilesha West', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (616, N'Osun', N'Irepodun', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (617, N'Osun', N'Irewole', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (618, N'Osun', N'Isokan', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (619, N'Osun', N'Iwo', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (620, N'Osun', N'Obokun', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (621, N'Osun', N'Odo-Otin', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (622, N'Osun', N'Ola-Oluwa', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (623, N'Osun', N'Olorunda', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (624, N'Osun', N'Oriade', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (625, N'Osun', N'Orolu', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (626, N'Osun', N'Osogbo', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (627, N'Oyo', N'Afijio', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (628, N'Oyo', N'Akinyele', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (629, N'Oyo', N'Atiba', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (630, N'Oyo', N'Atigbo', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (631, N'Oyo', N'Egbeda', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (632, N'Oyo', N'IbadanCentral', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (633, N'Oyo', N'Ibadan North', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (634, N'Oyo', N'Ibadan North West', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (635, N'Oyo', N'Ibadan South East', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (636, N'Oyo', N'Ibadan South West', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (637, N'Oyo', N'Ibarapa Central', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (638, N'Oyo', N'Ibarapa East', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (639, N'Oyo', N'Ibarapa North', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (640, N'Oyo', N'Ido', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (641, N'Oyo', N'Irepo', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (642, N'Oyo', N'Iseyin', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (643, N'Oyo', N'Itesiwaju', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (644, N'Oyo', N'Iwajowa', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (645, N'Oyo', N'Kajola', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (646, N'Oyo', N'Lagelu Ogbomosho North', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (647, N'Oyo', N'Ogbmosho South', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (648, N'Oyo', N'Ogo Oluwa', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (649, N'Oyo', N'Olorunsogo', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (650, N'Oyo', N'Oluyole', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (651, N'Oyo', N'Ona-Ara', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (652, N'Oyo', N'Orelope', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (653, N'Oyo', N'Ori Ire', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (654, N'Oyo', N'Oyo East', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (655, N'Oyo', N'Oyo West', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (656, N'Oyo', N'Saki East', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (657, N'Oyo', N'Saki West', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (658, N'Oyo', N'Surulere', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (659, N'Plateau', N'Barikin Ladi', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (660, N'Plateau', N'Bassa', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (661, N'Plateau', N'Bokkos', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (662, N'Plateau', N'Jos East', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (663, N'Plateau', N'Jos North', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (664, N'Plateau', N'Jos South', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (665, N'Plateau', N'Kanam', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (666, N'Plateau', N'Kanke', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (667, N'Plateau', N'Langtang North', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (668, N'Plateau', N'Langtang South', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (669, N'Plateau', N'Mangu', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (670, N'Plateau', N'Mikang', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (671, N'Plateau', N'Pankshin', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (672, N'Plateau', N'Qua''an Pan', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (673, N'Plateau', N'Riyom', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (674, N'Plateau', N'Shendam', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (675, N'Plateau', N'Wase', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (676, N'Rivers', N'Abua/Odual', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (677, N'Rivers', N'Ahoada East', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (678, N'Rivers', N'Ahoada West', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (679, N'Rivers', N'Akuku Toru', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (680, N'Rivers', N'Andoni', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (681, N'Rivers', N'Asari-Toru', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (682, N'Rivers', N'Bonny', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (683, N'Rivers', N'Degema', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (684, N'Rivers', N'Emohua', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (685, N'Rivers', N'Eleme', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (686, N'Rivers', N'Etche', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (687, N'Rivers', N'Gokana', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (688, N'Rivers', N'Ikwerre', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (689, N'Rivers', N'Khana', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (690, N'Rivers', N'Obia/Akpor', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (691, N'Rivers', N'Ogba/Egbema/Ndoni', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (692, N'Rivers', N'Ogu/Bolo', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (693, N'Rivers', N'Okrika', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (694, N'Rivers', N'Omumma', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (695, N'Rivers', N'Opobo/Nkoro', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (696, N'Rivers', N'Oyigbo', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (697, N'Rivers', N'Port-Harcourt', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (698, N'Rivers', N'Tai ', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (699, N'Sokoto', N'Binji', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (700, N'Sokoto', N'Bodinga', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (701, N'Sokoto', N'Dange-shnsi', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (702, N'Sokoto', N'Gada', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (703, N'Sokoto', N'Goronyo', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (704, N'Sokoto', N'Gudu', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (705, N'Sokoto', N'Gawabawa', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (706, N'Sokoto', N'Illela', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (707, N'Sokoto', N'Isa', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (708, N'Sokoto', N'Kware', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (709, N'Sokoto', N'kebbe', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (710, N'Sokoto', N'Rabah', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (711, N'Sokoto', N'Sabon birni', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (712, N'Sokoto', N'Shagari', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (713, N'Sokoto', N'Silame', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (714, N'Sokoto', N'Sokoto North', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (715, N'Sokoto', N'Sokoto South', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (716, N'Sokoto', N'Tambuwal', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (717, N'Sokoto', N'Tqngaza', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (718, N'Sokoto', N'Tureta', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (719, N'Sokoto', N'Wamako', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (720, N'Sokoto', N'Wurno', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (721, N'Sokoto', N'Yabo', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (722, N'Taraba', N'Ardo-kola', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (723, N'Taraba', N'Bali', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (724, N'Taraba', N'Donga', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (725, N'Taraba', N'Gashaka', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (726, N'Taraba', N'Cassol', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (727, N'Taraba', N'Ibi', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (728, N'Taraba', N'Jalingo', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (729, N'Taraba', N'Karin-Lamido', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (730, N'Taraba', N'Kurmi', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (731, N'Taraba', N'Lau', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (732, N'Taraba', N'Sardauna', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (733, N'Taraba', N'Takum', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (734, N'Taraba', N'Ussa', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (735, N'Taraba', N'Wukari', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (736, N'Taraba', N'Yorro', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (737, N'Taraba', N'Zing', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (738, N'Yobe', N'Bade', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (739, N'Yobe', N'Bursari', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (740, N'Yobe', N'Damaturu', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (741, N'Yobe', N'Fika', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (742, N'Yobe', N'Fune', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (743, N'Yobe', N'Geidam', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (744, N'Yobe', N'Gujba', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (745, N'Yobe', N'Gulani', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (746, N'Yobe', N'Jakusko', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (747, N'Yobe', N'Karasuwa', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (748, N'Yobe', N'Karawa', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (749, N'Yobe', N'Machina', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (750, N'Yobe', N'Nangere', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (751, N'Yobe', N'Nguru Potiskum', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (752, N'Yobe', N'Tarmua', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (753, N'Yobe', N'Yunusari', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (754, N'Yobe', N'Yusufari', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (755, N'Zamfara', N'Anka ', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (756, N'Zamfara', N'Bakura', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (757, N'Zamfara', N'Birnin Magaji', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (758, N'Zamfara', N'Bukkuyum', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (759, N'Zamfara', N'Bungudu', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (760, N'Zamfara', N'Gummi', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (761, N'Zamfara', N'Gusau', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (762, N'Zamfara', N'Kaura', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (763, N'Zamfara', N'Namoda', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (764, N'Zamfara', N'Maradun', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (765, N'Zamfara', N'Maru', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (766, N'Zamfara', N'Shinkafi', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (767, N'Zamfara', N'Talata Mafara', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (768, N'Zamfara', N'Tsafe', NULL)
GO
INSERT [dbo].[TBL_STATEANDLGA] ([ID], [STATE], [LGA], [STATEID]) VALUES (769, N'Zamfara', N'Zurmi ', NULL)
GO
SET IDENTITY_INSERT [dbo].[TBL_STATEANDLGA] OFF
GO
SET IDENTITY_INSERT [dbo].[TblCustomer] ON 
GO
INSERT [dbo].[TblCustomer] ([ID], [AccountNumber], [Firstname], [Othernames], [Surname], [Email], [Phone], [Addressid]) VALUES (1, N'09263773', N'Peter', N'Sunday', N'Okereke', N'sunny.okereke@gmail.com', N'08096682900', 2)
GO
SET IDENTITY_INSERT [dbo].[TblCustomer] OFF
GO
USE [master]
GO
ALTER DATABASE [OnboardAPI] SET  READ_WRITE 
GO
