// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PeterOnboardCustomer.Data
{
    public partial class TblCustomer
    {
        public int Id { get; set; }
        public string AccountNumber { get; set; }
        public string Firstname { get; set; }
        public string Othernames { get; set; }
        public string Surname { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public int? Addressid { get; set; }
    }
}