// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PeterOnboardCustomer.Data
{
    public partial class TblCustomeraddress
    {
        public int? Id { get; set; }
        public int? Customerid { get; set; }
        public int? Stateid { get; set; }
        public string Address { get; set; }
        public string Hometown { get; set; }
        public string Pobox { get; set; }
        public string Country { get; set; }
    }
}