// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PeterOnboardCustomer.Data
{
    public partial class TblStateandlga
    {
        public int Id { get; set; }
        public string State { get; set; }
        public string Lga { get; set; }
        public int? Stateid { get; set; }
    }
}